# Generated by Django 5.0.6 on 2024-06-04 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='food_order_app.foodcategory'),
        ),
        migrations.RenameField(
            model_name='fooditems',
            old_name='category',
            new_name='category_id',
        ),
    ]
